language: python

python:
  - "3.4"

# Build inside docker containers instead of virtual machines. These are
# faster, start quicker and support caching. Only downside: sudo is not
# supported. To work around this, the debian package must be extracted
# manually and a few environment variables need to be set up (see below).
sudo: false

env:
  global:
    # Enable caching of python wheels
    - PIP_FIND_LINKS=file://$HOME/.pip-cache
    - PIP_WHEEL_DIR=$HOME/.pip-cache

    # download binary GLPK
    - PREFIX=$HOME/install
    - RPATH=$PREFIX/usr/lib/x68_64-linux-gnu
    - IPATH=$PREFIX/usr/include

install:
  - apt-get download libglpk-dev
  - dpkg -x libglpk-dev* $PREFIX
  - pip install cython
  - python setup.py build_ext -R $RPATH -I $IPATH

script:
  - nosetests

cache:
  apt: true
  directories:
    - $PIP_WHEEL_DIR
